# Generated by Django 3.0.1 on 2020-01-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstName', models.CharField(max_length=25)),
                ('userLastName', models.CharField(max_length=25)),
                ('userGender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=5)),
                ('userQualification', models.CharField(choices=[('bsc', 'BSc'), ('bca', 'BCA'), ('bba', 'BBA'), ('btech', 'BTech'), ('msc', 'MSc')], max_length=5)),
                ('userEmailId', models.EmailField(max_length=100, unique=True)),
                ('userMobileNo', models.CharField(max_length=12)),
                ('userPasswsord', models.CharField(max_length=15)),
                ('userJoiningCompleted', models.BooleanField(default=False)),
                ('userAddedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
